version: '3.4'

services:
  presentation:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString:Server=presentationdb;Port=4022;Database=myDataBase;User Id=sa;Password=Aslan!123456789;TrustServerCertificate=true;"
    depends_on:
      - presentationdb
    ports:
      - "8002:80"
  presentationdb:
    container_name: presentationdb
    environment:
        - "MSSQL_SA_PASSWORD=Aslan!123456789"
        - ACCEPT_EULA=Y
    restart: always
    ports:
        -  "4022:1433"