version: '3.4'

services:
  presentation:
    image: ${DOCKER_REGISTRY-}presentation
    build:
      context: .
      dockerfile: src/Presentation/Dockerfile

  presentationdb:
    image: mcr.microsoft.com/mssql/server:2019-latest